version: '2.9'

services:
  db:
   image: postgres:14.4-alpine
   container_name: kimgech_db
   ports:
    - '7432:5432'
#   networks:
#    - kimgech
   environment:
    - POSTGRES_DB=mydb
    - POSTGRES_USER=myuser
    - POSTGRES_PASSWORD=mypass
#   volumes:
#    - data:/var/lib/postgresql/data
#  volumes:
#    data:
#     driver: local